### ISSUE TITLE
PXD-6 ⁃ feat(jwt): copy from user-api and implement oauth2 authentication using JWT

### ISSUE THREAD

**Issue by skattar1406** [philloooo/github-tests#215]
Resolves PXD-5.

Currently, result from `/keys` endpoint looks like:

```
{
  "keys": [
    {
      "key-01": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtnIijCXy3dWBvrZFk8T5\ngmd0IObp/Wr9q18ikhmJcmRMIcViHtP81FftignbQ/ulchu53R3SuVpDL79wt0XJ\nBy3xLwj0pgHyY2Ut7VT7izk6s2Ucrk9tfkBB0K81U/VlG0S6b4R6zS/ayex2vlEF\no6On0smMRjKbHQKi1POp6LDKkGQTHBW6fhVdVkIXpomqUh0nvaZ+fFuycGL7yHsh\nPuEqHa0sCNNv6+vLWQMjBZqLJJg/EZd5wI6QgKyryN0KkzdW+rxhlYER8f49H5an\nSJUiaDF2Mbn5X7E3o4eclQ5TQxT9T6HHmFPYU/nLXv3xiMkTjAF2bxPty3rNTFfv\nWlEyF58tQDa6KjV0EM0+7eS1gEXPCCtSpM9vfCo/a9OEu08vnWeAA3Wi75Oyb6oO\ndsreTIMJnIYODBowYOo5C5ozCVhs82RYMY+7YgqN2NpM59yuLhQyASSKshNz754b\nIKsn5q3H9ClL7SjnJsj8Hd+X+7hAyxxYdzWAiA13OjSGkh7ySB0YnJGbyzLUKmB/\n5km5jfjGTEqJw6lnFRFDQlvZXqZxlFxHTMCmPAOBqJq3+IoSrlniPrrXEPX0bApT\nj2/QBxQvywBDofZko3kQ57uRIeKdfzBSmsNDqcHxiSBcKAGk7MumjmW9nFPeJxnF\n2ba7AKvkwotPMsOXsJfIi/ECAwEAAQ==\n-----END PUBLIC KEY-----\n"
    }
  ]
}
```

so that cdispyutils can get the keys back into an ordered dictionary (where the first key in the list is the default, and keys can be identified by key id).

### TODO
* [x] Fix `setup.py`/`requirements.txt`
* [x] Add public key endpoint
* [x] Revise public key config to set up a dictionary of public keys
* [x] Add table for blacklisted tokens
* [x] Support revoking token issued from oauth using blacklist table

**Comment by skattar1406** [comment]
➤ Phillis Tang commented:

needs dockerfile and quay hook

**Comment by skattar1406** [comment]
➤ Rudyard Richter commented:

Dockerfile added in b800f26. Quay hook added on quay.io.
